Replace usage of np.float with float (#147) (#150)
The epr_numerical_diagonalization function uses np.float which has been
deprecated in Numpy.

Refer https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

The continued usage of np.float yields the following error in the
epr_numerical_diaganolization function when later versions of Numpy is used.

"AttributeError: module 'numpy' has no attribute 'float'."

This commit replace np.float with float to solve this error.